services:
  app:
    build:
      context: ./laravel-with-docker
      dockerfile: Dockerfile.dev
    volumes:
      - ./laravel-with-docker:/var/www/html
    ports:
      - 9000:9000
    depends_on:
      - db
      - redis
    networks:
      - docker-network

  vite:
    build:
      context: ./laravel-with-docker
      dockerfile: Dockerfile.dev
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./laravel-with-docker:/var/www/html
    ports:
      - 5173:5173
    depends_on:
      - app
    networks:
      - docker-network

  queue:
    build:
      context: ./laravel-with-docker
      dockerfile: Dockerfile.dev
    command: php artisan queue:work
    volumes:
      - ./laravel-with-docker:/var/www/html
    depends_on:
      - db
      - redis
    networks:
      - docker-network
      
  caddy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./laravel-with-docker/public:/var/www/html/public
    depends_on:
      - app
    networks:
      - docker-network

  db:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
    volumes:
      - db-data:/bitnami/postgresql
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - docker-network

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - redis-data:/bitnami/redis/data
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge

volumes:
  db-data:
  redis-data:
